# Generated by Django 5.0.1 on 2024-01-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(help_text='Enter PAN number', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Enter member name', max_length=255)),
            ],
        ),
    ]
