# Generated by Django 5.0.1 on 2024-01-12 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status_member',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amal', models.PositiveBigIntegerField(default=0)),
                ('jam_absen', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.member')),
            ],
        ),
    ]
